
networks:
  app:
services:
  backend:
    build: 
      context: ./backend
    ports:
      - 8000:8000
    networks:
      - app
  frontend:
    build: 
      context: ./frontend/childrenapp
    ports:
      - 3000:3000
    networks:
      - app
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app
    
    
    