
networks:
  app:
services:
  backend:
    build: 
      context: ./backend
    command: ./main
    networks:
      - app
  frontend:
    build: 
      context: ./frontend
    networks:
      - app
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app
    
    